### ISSUE TITLE
channel_id does not exist

### ISSUE THREAD

**Issue by phiweger** [mbhall88/bam2fast5#5]
I try to run fast5seek like so:

```bash
fast5seek -i path/to/signal -r ref.fq -o result.txt
```

However, it fails (always at different percent complete points):

```python
[07/03/2018 12:43:56 PM]:INFO: Scanning 423989 fast5 files for presence in references
Percent: [#####-----------------------------------] 11.29% Traceback (most recent call last):
  File ".../miniconda3/envs/tombo/bin/fast5seek", line 11, in <module>
    sys.exit(cli())
  File ".../miniconda3/envs/tombo/lib/python3.6/site-packages/fast5seek/cli.py", line 105, in cli
    fast5seek.main(args)
  File ".../miniconda3/envs/tombo/lib/python3.6/site-packages/fast5seek/fast5seek.py", line 316, in main
    write_progress_bar_to)
  File ".../miniconda3/envs/tombo/lib/python3.6/site-packages/fast5seek/fast5seek.py", line 232, in collect_present_fast5_filepaths
    fast5_read_id, fast5_run_id = get_read_and_run_id(filepath)
  File ".../miniconda3/envs/tombo/lib/python3.6/site-packages/fast5seek/fast5seek.py", line 49, in get_read_and_run_id
    fast5 = Fast5File(filepath)
  File ".../miniconda3/envs/tombo/lib/python3.6/site-packages/ont_fast5_api/fast5_file.py", line 70, in __init__
    self.status = Fast5Info(self.filename)
  File ".../miniconda3/envs/tombo/lib/python3.6/site-packages/ont_fast5_api/fast5_info.py", line 80, in __init__
    self.channel = handle['UniqueGlobalKey/channel_id'].attrs.get('channel_number')
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-gkjbrkhs-build/h5py/_objects.c:2840)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-gkjbrkhs-build/h5py/_objects.c:2798)
  File ".../miniconda3/envs/tombo/lib/python3.6/site-packages/h5py/_hl/group.py", line 169, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-gkjbrkhs-build/h5py/_objects.c:2840)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-gkjbrkhs-build/h5py/_objects.c:2798)
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open (/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-gkjbrkhs-build/h5py/h5o.c:3734)
KeyError: "Unable to open object (Object 'channel_id' doesn't exist)"
```

What could be the problem here? I did use Tombo on these files, and is has a flag in the resquiggle command to ignore locked hdf5 files -- might this be the problem?

Could fast5seek be adjusted to either unlock such files (if this is the problem) or simple catch the error, report it ("could not process x") and continue?

Thanks,
Adrian

**Comment by mbhall88** [comment]
Hi Adrian,

It looks to me like there is some issue with the fast5 file it is trying to search. I use [ONT's fast5 api package](https://github.com/nanoporetech/ont_fast5_api) to handle fast5 files and it appears as though the error is coming from my call to that package.  
I think it would be best to open an issue on their repository.  

I could obviously add a catch for the error ([here](https://github.com/mbhall88/fast5seek/blob/83861e1c152572023bdb1a6b93626aacd6177575/fast5seek/fast5seek.py#L52)), but I feel like this is something which should be handled on the fast5 API instead.  

Do you happen to know which fast5 file is causing the problem?

**Comment by phiweger** [comment]
Thanks for looking into this. 

Sadly, I am not able to track the exact file that causes the problem. When run on a fresh backup of the raw data, fast5seek completes w/o errors. I guess I will stick to this workaround for now.

**Comment by mbhall88** [comment]
Ok. Sounds to me like `tombo` may not be adding some required information into the new fast5 files it generates (as I think you allude to in the referenced issue).  

Let me know if there is anything I can do.
