### ISSUE TITLE
UnboundLocalError: local variable 'global_keys' referenced before assignment

### ISSUE THREAD

**Issue by YingziZhang-github** [mbhall88/bam2fast5#7]
Hi,
Thank you very much for developing fast5seek. It is the only available tool I find to extract fastq5 from fastq files. Your help of this issue will be very appreciated.

The cmd I used was `fast5seek -i /nanopore/minknow/data/20220720_1052_MN30213_FAQ39030_a7c337e6/fast5_pass/ -r readname.fastq -o test.txt --log_level 4`.

The error report is this:
```
[03/28/2023 08:53:27 PM]:INFO: Starting fast5seek.
[03/28/2023 08:53:27 PM]:INFO: Looking for reads to extract in the following ref files:
[03/28/2023 08:53:27 PM]:INFO: readname.fastq
[03/28/2023 08:53:27 PM]:INFO: Found 359 unique read ids
[03/28/2023 08:53:27 PM]:INFO: Found 8 fast5 files.
[03/28/2023 08:53:27 PM]:INFO: Scanning 8 fast5 files for presence in references
Traceback (most recent call last):
  File "/home/zhany0s/software/anaconda3/envs/Methylation/lib/python3.10/site-packages/ont_fast5_api/fast5_file.py", line 277, in _initialise_file
    self.status = Fast5Info(self.filename)
  File "/home/zhany0s/software/anaconda3/envs/Methylation/lib/python3.10/site-packages/ont_fast5_api/fast5_info.py", line 77, in __init__
    if 'tracking_id' not in global_keys and not self._legacy_version():
UnboundLocalError: local variable 'global_keys' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhany0s/software/anaconda3/envs/Methylation/bin/fast5seek", line 10, in <module>
    sys.exit(cli())
  File "/home/zhany0s/software/anaconda3/envs/Methylation/lib/python3.10/site-packages/fast5seek/cli.py", line 105, in cli
    fast5seek.main(args)
  File "/home/zhany0s/software/anaconda3/envs/Methylation/lib/python3.10/site-packages/fast5seek/fast5seek.py", line 315, in main
    final_filepath_list = collect_present_fast5_filepaths(fast5_filepaths,
  File "/home/zhany0s/software/anaconda3/envs/Methylation/lib/python3.10/site-packages/fast5seek/fast5seek.py", line 232, in collect_present_fast5_filepaths
    fast5_read_id, fast5_run_id = get_read_and_run_id(filepath)
  File "/home/zhany0s/software/anaconda3/envs/Methylation/lib/python3.10/site-packages/fast5seek/fast5seek.py", line 49, in get_read_and_run_id
    fast5 = Fast5File(filepath)
  File "/home/zhany0s/software/anaconda3/envs/Methylation/lib/python3.10/site-packages/ont_fast5_api/fast5_file.py", line 42, in __init__
    self._initialise_file()
  File "/home/zhany0s/software/anaconda3/envs/Methylation/lib/python3.10/site-packages/ont_fast5_api/fast5_file.py", line 281, in _initialise_file
    raise Fast5FileTypeError("Failed to initialise single-read Fast5File: '{}'".format(self.filename))
ont_fast5_api.fast5_file.Fast5FileTypeError: Failed to initialise single-read Fast5File: '/nanopore/minknow/data/20220720_1052_MN30213_FAQ39030_a7c337e6/fast5_pass/FAQ39030_pass_ebc85fce_6.fast5'
```

Would you let me know how can I solve this problem?

Many thanks in advance,

**Comment by mbhall88** [comment]
Hi,

I haven't touched this tool for four and a half years sorry. As such I suspect the fast5 file structure has changed quite a bit.

The functionality of this tool is pretty much replaced by [`fast5_subset`](https://github.com/nanoporetech/ont_fast5_api#fast5_subset) anyway. Extract your read names from your fastq into a text file and then use that as input to `fast5_subset`.

**Comment by YingziZhang-github** [comment]
Hi Michael,

Thank you for answering. fast5_subset works very well. Many thanks!
